### ISSUE TITLE
Changing font size doesn't influence some texts from the app

### ISSUE THREAD

**Issue by anghelalexandra** [appticles/theme-obliq#13]
The following texts sizes don't change when editing the global font size setting:

- [x] page title (from page details)
- [x] "Comments" and "Leave a comment" titles
- [x] comments (author, date, comment text)
- [x] side menu items

Regarding the page title, can we also make the default size larger?

**Comment by mihaisavezi** [comment]
* page title(from page details) font size is fixed to keep alignment with the close button.

![image](https://cloud.githubusercontent.com/assets/6965490/24404712/f4271c56-13ca-11e7-8943-c8a5c98f2817.png)

* "Comments" and "Leave a comment" titles font-size is fixed to contain font to fixed height topBar.

![image](https://cloud.githubusercontent.com/assets/6965490/24404773/3600cd16-13cb-11e7-94db-47646f01d74f.png)

* comments (author, date, comment text). Author and date are fixed to maintain alignment to fixed height, width imageAvatar. Can't reproduce this for comment text.

![image](https://cloud.githubusercontent.com/assets/6965490/24405044/17ea6f52-13cc-11e7-8ae5-790909f86329.png)

* side menu items fixed font-size. Some elements in the sideMenu are constrained to a fixedHeight, so to maintain consistency between items that have a fixedHeight and items that don't, this decision was taken where font-sizing shouldn't affect the sideMenu.

**Comment by mihaisavezi** [comment]
fix pageDetails title height after discussion
