### ISSUE TITLE
Do we have some calculations for the featured images on the old version?

### ISSUE THREAD

**Issue by anghelalexandra** [appticles/theme-obliq#16]
For comparison, old version:

<img width="282" alt="screen shot 2017-03-28 at 2 46 30 pm" src="https://cloud.githubusercontent.com/assets/3062304/24403423/7a8782c8-13c5-11e7-80a8-f73d907d95eb.png">

vs. new version:

<img width="281" alt="screen shot 2017-03-28 at 2 46 40 pm" src="https://cloud.githubusercontent.com/assets/3062304/24403437/87266698-13c5-11e7-8587-a07afdc8b0b8.png">

**Comment by mihaisavezi** [comment]
Yes, there were calculation in the previous version before the template was rendered
